### ISSUE TITLE
Receiving messages from server in multiplayer causes the game to freeze.

### ISSUE THREAD

**Issue by etianl** [JFronny/MeteorAdditions#24] opened 2023-03-12 04:44 UTC
Whenever any message is received from the server, the game freezes up for a moment. If the server is spamming messages, such as when I am spamming /fill commands and the server talks back about where is filled it can freeze the game to the point of the client crashing entirely due to memory overload or something. No crash report gets given which is annoying. I had to remove Meteor Additions from my mods folder due to this issue, and I will await a fix to re-include it in the mods I use

**Comment by etianl** [comment] 2023-03-12 04:47
Right, I just remembered once the Translator module was working despite the module being turned off? My game also freezes up for a second when translating messages with that which isn't a big deal if it's only when translating chat messages. I believe the issue in the previous message here may be in relation to the code in the Translator module

**Comment by JFronny** [comment] 2023-03-12 09:18
If I understand the problem correctly, just caching the last few translations should be an easy workaround for this, no?
Also: some versions of this addon require you to enable and then re-disable the translator module to properly sync its state.
That should be fixed in the latest versions, though.

**Comment by JFronny** [comment] 2023-03-12 09:20
You can also use the existing regex filter to ignore those messages

**Comment by etianl** [comment] 2023-03-12 19:17
Using the latest version of your modpack still results in the same issue, I tried to update it. The issue is that whenever any message is sent from the server I believe the translator module is attempting to translate it despite it not even being a chat message all the time, and despite the translator module not even being on. This is in theory, I have no idea what's actually happening. What I observe is that whenever meteoradditions is in my mods folder the game will be freezing every time a server message is received in a multiplayer world, which can lead to the game crashing

**Comment by JFronny** [comment] 2023-03-12 20:56
Then enable and re-disable the module once, as I said.
Are the messages close to the same so that a cache would work?

**Comment by etianl** [comment] 2023-03-12 22:11
The server messages translated from english to english are the same I think, so much so I had no idea it was translater doing the freezing at first. Opening a world, then enabling and disabling the module as you suggest fixes it until the next time the game is launched

**Comment by JFronny** [comment] 2023-07-28 12:12
Considering the changes I made to this module and the backing mod after this was opened, I believe it is likely that this is no longer relevant to the latest 1.20.1 release.
If the problem is still present in that version, please reopen this issue.

**Closed by JFronny** 2023-07-28 12:12 UTC
